-- Script para criação da tabela de endereço

CREATE TABLE ENDERECO(
ID UNIQUEIDENTIFIER PRIMARY KEY,
LOGRADOURO VARCHAR(150) NOT NULL,
NUMERO VARCHAR(15) NOT NULL,
BAIRRO VARCHAR(50) NOT NULL,
LOCALIDADE VARCHAR(100) NOT NULL,
UF CHAR(2) NOT NULL,
CEP VARCHAR(10) NOT NULL);
GO

-- script para criação da tabela funcionario

CREATE TABLE FUNCIONARIO (
ID UNIQUEIDENTIFIER PRIMARY KEY,
NOME VARCHAR(150) NOT NULL,
CPF VARCHAR(14) NOT NULL,
MATRICULA VARCHAR(15) NOT NULL,
DATAADMISSAO DATE NOT NULL,
SALARIO DECIMAL(10,2) NOT NULL,
CARGO INT NOT NULL,
ENDERECO_ID UNIQUEIDENTIFIER NOT NULL,
FOREIGN KEY(ENDERECO_ID)
REFERENCES ENDERECO(ID),
CHECK (CARGO BETWEEN 1 AND 6));
GO


--SCRIPT PARA CRIAR UMA PROCEDURE DE CADASTRO DE FUNCIONARIO E ENDEREÇO

CREATE PROCEDURE SP_INSERIR_FUNCIONARIO
@NOME VARCHAR(150),
@CPF VARCHAR(14),
@MATRICULA VARCHAR(15),
@DATAADMISSAO DATE,
@SALARIO DECIMAL(10,2),
@CARGO INT,
@LOGRADOURO VARCHAR(150),
@NUMERO VARCHAR(15),
@BAIRRO VARCHAR(50),
@LOCALIDADE VARCHAR(100),
@UF CHAR(2),
@CEP VARCHAR(10)

AS
BEGIN
 BEGIN TRANSACTION --ABRINDO UMA TRANSAÇÃO

 -- CRIANDO OS IDS DO FUNCIONARIO E DO ENDEREÇO
 DECLARE @IDFUNCIONARIO UNIQUEIDENTIFIER = NEWID();
 DECLARE @IDENDERECO UNIQUEIDENTIFIER = NEWID();

 -- GRAVAR OS DADOS DO ENDERECO
 INSERT INTO ENDERECO(ID, LOGRADOURO, NUMERO, BAIRRO, LOCALIDADE, UF, CEP)
 VALUES(@IDENDERECO, @LOGRADOURO, @NUMERO, @BAIRRO, @LOCALIDADE, @UF, @CEP);

 --GRAVAR OS DADOS DO FUNCIONARIO
 INSERT INTO FUNCIONARIO (ID, NOME, CPF, MATRICULA, DATAADMISSAO, SALARIO, CARGO, ENDERECO_ID)
 VALUES(@IDFUNCIONARIO, @NOME, @CPF, @MATRICULA, @DATAADMISSAO, @SALARIO, @CARGO, @IDENDERECO);


 COMMIT -- FINALIZANDO A TRANSAÇÃO
END;
GO
